### ISSUE TITLE
Merch

### ISSUE THREAD

**Issue by aleksey2299-1** [BittWizards/backend#2]
Описать модели, написать сериализаторы, views.
Добавить все в админку.
Для функций подключаем типизацию, где нужно используем gettext_lazy.
Можно порционно заливать pr.

**Comment by pashpiter** [comment]
Скажу что сомневаюсь что это можно описать все за 2 дня (в целом про объем) и + еще 23-е февраля)

**Comment by aleksey2299-1** [comment]
Я этот сделаю за день, умножаем на 2 из расчета на что-то непредвиденное (но я не увидел тут ничего сложного, добавим еще что вы не первый день хакатонствуете), итого выходит 8 часов.
Добавлю от себя что не обязательно сделать все идеально, pytest окей можно не сразу запилить, но стоит учесть что я себе не выделил задачу, и если не сделаете вы, это сделаю я.
Сомневаетесь? Можете не брать. Я лично ни в себе, ни в вас не сомневаюсь (но вы можете легко заставить меня разочароваться, также как я разочаруюсь в себе если не сделаю это за день).
