### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by aleksey2299-1** [BittWizards/backend#6]
Стоит автодокументация, но все все мы понимаем что выглядеть она будет не презентабельно.
Задача состоит в описании примеров, ошибок, всего что превратит эту жабу в принцессу.
Работать предстоит с drf-spectacular.
Это задача получит высокий приоритет под конец. Пока что ее можно просто забронировать и заниматься понемногу.
Дедлайн 09.03 10:00. После этого времени этим уже займется не только лишь 1 человек.

**Comment by pashpiter** [comment]
Я накидал каркас для openapi, залью со своей веткой "orders"
