### ISSUE TITLE
Yandex Forms

### ISSUE THREAD

**Issue by aleksey2299-1** [BittWizards/backend#8]
Без комментариев.
Задача: разобраться что это такое, как интегрировать, протестировать и определить какие задачи мы можем этим закрыть.
Задача достаточно плохо представлена мною, скорее всего потребуются еще данные.
Когда бы я хотел иметь представление что нам с этим делать - 28.02
Дэдлайн 03.03.

**Comment by pashpiter** [comment]
Так а это нужно вообще?)

**Comment by aleksey2299-1** [comment]
Возможно и не нужно, но мы не поймем наверняка, пока кто-нибудь, кто в этом разобрался, нам этого не скажет

**Comment by KlavaD** [comment]
надо создать формы, такие же: https://forms.yandex.ru/surveys/13477860.c94a0e28ca5059ca34dc4210d4a35008780740a7/
https://forms.yandex.ru/surveys/13457507.23ad270400fa26cc48f562e756f68cf9c6352e8e/
и настроить их на наш апи.
для этого конечно надо написать апи
